### ISSUE TITLE
`stack-clean-old keep-minor` while stack is installing ghc

### ISSUE THREAD

**Issue by andreasabel** [juhp/stack-clean-old#13] opened 2023-01-14 20:57 UTC
While `stack` is still installing GHC 9.4.4, I ran `stack-clean-old keep-minor` and got the following output:
```
$ stack-clean-old keep-minor 
ghc-9.2.4 compiler would be removed
ghc-9.4.3 compiler would be removed
ghc-9.4.4.temp compiler would be removed
...
```
Maybe the last one is unexpected here.  There is no GHC > 9.4.4 so maybe `keep-minor` should not include this unfinished GHC installation in its removal list.

**Comment by juhp** [comment] 2023-05-31 05:59
Good catch, I haven't tried that

**Comment by juhp** [comment] 2023-08-27 12:59
I can't reproduce this anymore I think - we can probably close it?

Can you try again now?

```shellsession
$ mkdir ~/.stack/programs/x86_64-linux/ghc-tinfo6-9.6.3.temp/
$ stack-clean-old list -C 9.6
ghc-tinfo6-9.6.1
ghc-tinfo6-9.6.2
ghc-tinfo6-9.6.3.temp
$ stack-clean-old keep-minor -C | grep 9.6
ghc-tinfo6-9.6.1 compiler would be removed
ghc-tinfo6-9.6.2 compiler would be removed
```

Anyway while testing I found a more serious bug perhaps: that `stack-clean-old keep-minor -C 9.6` does nothing.
I opened #17 .

**Closed as completed** 2023-12-17 06:22 UTC
